name: Scheduled Tests

on:
  schedule:
    # Run tests every day at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scheduled-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run comprehensive tests
        run: |
          npm run check
          npm run test:run
          npm run test:coverage
          npm run build
          
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Scheduled Tests Failed',
              body: `The scheduled tests failed on ${new Date().toISOString()}.
              
              Please check the [workflow run](${context.payload.repository.html_url}/actions/runs/${context.runId}) for details.
              
              This issue was automatically created by the scheduled test workflow.`,
              labels: ['bug', 'scheduled-test-failure']
            });
            
            console.log(`Created issue #${issue.data.number}`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
